---
title: "p8105_hw5_Ic3391.Rmd"
author: "Lu Chen"
date: "11/10/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## Problem 1 
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

# replacing missing values for both numeric and character variables

na_replace = function(vec) {
  if (is.numeric(vec)) {
    vec = replace(vec, is.na(vec), round(mean(vec, na.rm = TRUE)))
  }
  else if (is.character(vec)) {
    vec = replace(vec, is.na(vec), "virginica")
  }
  vec #return the resulting vector
}

map (iris_with_missing,na_replace)

```

## Problem 2
```{r warning=FALSE}
tibble(list.files(path = "./data")) %>% 
  rename(id_and_arm = `list.files(path = "./data")`) %>% 
  mutate(add_up = "./data/", change_wd = str_c(add_up, id_and_arm), data = map(change_wd, read.csv)) %>% 
  unnest() %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "value"
    ) %>% 
  subset.data.frame(select = c("id_and_arm","week","value")) %>% 
  ggplot(aes(x = week, y = value, group = id_and_arm, color = id_and_arm)) +
  geom_line() +
  facet_grid(.~id_and_arm) +
  labs(
    title = "Observations over time",
    x = "Week", 
    y = "Value"
    ) 

#comments: In general, the experiment group receives higher value compared to the control group.Participants in the experiment group have a great improvement in values at certain observation time period.
  
```

## Problem 3
```{r}
#hypothesis testing

sim_regression = function(n=30, beta0=2, beta1=0){
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 50)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta1_hat = coef(ls_fit)[2],
    p_value = broom::tidy(ls_fit)[[2,5]]
  )
}

sim_regression()

s_0 = 
  rerun(10000, sim_regression(30, 2, 0)) %>% 
  bind_rows() %>% 
  mutate (beta = 0) 

sim_results_0 = 
  s_0 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000) %>% 
  mutate (beta = 0) 

ss_0 = 
  rerun(10000, sim_regression(30, 2, 0)) %>% 
  bind_rows() %>% 
  mutate (beta = 0) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))

s_1 = 
  rerun(10000, sim_regression(30, 2, 1)) %>% 
  bind_rows() %>% 
  mutate (beta = 1)  

sim_results_1 =
  s_1 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000)  %>% 
  mutate (beta = 1) 

ss_1 = 
  rerun(10000, sim_regression(30, 2, 1)) %>% 
  bind_rows() %>% 
  mutate (beta = 1) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))

s_2 =
  rerun(10000, sim_regression(30, 2, 2)) %>% 
  bind_rows() %>% 
  mutate (beta = 2) 

sim_results_2 = 
  s_2 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000) %>% 
  mutate (beta = 2)

ss_2 = 
  rerun(10000, sim_regression(30, 2, 2)) %>% 
  bind_rows() %>% 
  mutate (beta = 2) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))


s_3 = 
  rerun(10000, sim_regression(30, 2, 3)) %>% 
  bind_rows() %>% 
  mutate (beta = 3)  

sim_results_3 = 
  s_3 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000) %>% 
  mutate (beta = 3)

ss_3 = 
  rerun(10000, sim_regression(30, 2, 3)) %>% 
  bind_rows() %>% 
  mutate (beta = 3) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))


s_4 =
  rerun(10000, sim_regression(30, 2, 4)) %>% 
  bind_rows() %>% 
  mutate (beta = 4)

sim_results_4 = 
  s_4 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000)  %>% 
  mutate (beta = 4)

ss_4 = 
  rerun(10000, sim_regression(30, 2, 4)) %>% 
  bind_rows() %>% 
  mutate (beta = 4) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))

s_5 = 
  rerun(10000, sim_regression(30, 2, 5)) %>% 
  bind_rows() %>% 
  mutate (beta = 5)

sim_results_5 = 
  s_5 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000)  %>% 
  mutate (beta = 5)

ss_5 = 
  rerun(10000, sim_regression(30, 2, 5)) %>% 
  bind_rows() %>% 
  mutate (beta = 5) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))

s_6 = 
  rerun(10000, sim_regression(30, 2, 6)) %>% 
  bind_rows() %>% 
  mutate (beta = 6)

sim_results_6 = 
  s_6 %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0")) %>% 
  summarize(n_significane = sum(as.numeric(significane))) %>% 
  mutate(proportion = n_significane/10000) %>% 
  mutate (beta = 6) 

ss_6 = 
  rerun(10000, sim_regression(30, 2, 6)) %>% 
  bind_rows() %>% 
  mutate (beta = 6) %>% 
  mutate(significane = case_when(p_value < 0.05 ~ "1", TRUE ~ "0"))

sim_results_6

t = bind_rows(sim_results_0,sim_results_1,sim_results_2,sim_results_3,sim_results_4,sim_results_5,sim_results_6) 
  
ggplot(t, aes(x = beta, y = proportion)) +
geom_bar(stat = 'identity') +
labs(
  title = "Proportion of significance on each beta",
  x = "Beta", 
  y = "Proportion of significance"
) 

# comments: when the beta increases, the proportion of significance increases, meaning the effect size and power are postively associated.

# average estimated beta1

t_2 = bind_rows(s_0, s_1, s_2, s_3, s_4, s_5, s_6)

t_2 %>% 
  group_by(beta) %>% 
  summarize(mean_beta1 = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta, y = mean_beta1)) +
  geom_point() +
  labs(
   title = "Average estimated beta vs. true beta",
   x = "True Beta", 
    y = "Average estimated beta"
  ) 

t_3= bind_rows(ss_0, ss_1, ss_2, ss_3, ss_4, ss_5, ss_6)

t_3 %>% 
  filter(significane %in% c("1")) %>% 
  group_by(beta) %>% 
  summarize(mean_beta1 = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta, y = mean_beta1)) +
  geom_point() +
  labs(
   title = "Average estimated beta vs. true beta in samples for which the null was rejected",
   x = "True Beta", 
    y = "Average estimated beta"
  ) 

# comments: The sample average of beta1 across tests for which the null is rejected is not approximately equal to the true value of beta1. One reason is that the effect size influences the power. When we have greater effect size, for example, when beta1 = 6, we might have 8000 samples significiant, which leads to a biased result. 
  

```

